table HealthData
	lineageTag: a0149ef8-aa2e-400f-b600-f5ff0da7de7b

	column 'Patient ID'
		dataType: string
		lineageTag: aaf947e7-a2ab-4c9d-beae-da1a1232f83a
		summarizeBy: none
		sourceColumn: Patient ID

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 4e7f2451-a360-403e-b69d-c1f7ea444e12
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: a29d9b0e-b36a-4add-aad3-073f34f66e12
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Blood Type'
		dataType: string
		lineageTag: 5cef6f08-9b71-4d4f-98ce-f542303649f5
		summarizeBy: none
		sourceColumn: Blood Type

		annotation SummarizationSetBy = Automatic

	column 'Date of Admission'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0731e079-3b1c-4301-8022-91bd308bdf10
		summarizeBy: none
		sourceColumn: Date of Admission

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Doctor
		dataType: string
		lineageTag: f5fc7fd2-4d54-4b0c-b958-54c22dcbc987
		summarizeBy: none
		sourceColumn: Doctor

		annotation SummarizationSetBy = Automatic

	column Hospital
		dataType: string
		lineageTag: 47ff7365-c6bb-414e-b332-00ea356fb01b
		summarizeBy: none
		sourceColumn: Hospital

		annotation SummarizationSetBy = Automatic

	column 'Insurance Provider'
		dataType: string
		lineageTag: 89ca44ad-82a9-4c24-9a9c-cf8822f758cb
		summarizeBy: none
		sourceColumn: Insurance Provider

		annotation SummarizationSetBy = Automatic

	column 'Billing Amount'
		dataType: double
		lineageTag: 991e008c-c2d6-450e-a715-29127e8cb9ef
		summarizeBy: sum
		sourceColumn: Billing Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Room Number'
		dataType: int64
		formatString: 0
		lineageTag: d119baec-afb3-4971-917d-ddc5bac2e64d
		summarizeBy: sum
		sourceColumn: Room Number

		annotation SummarizationSetBy = Automatic

	column 'Admission Type'
		dataType: string
		lineageTag: 98c17a76-cb70-4d60-b857-86b58b174f7b
		summarizeBy: none
		sourceColumn: Admission Type

		annotation SummarizationSetBy = Automatic

	column 'Discharge Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ada1f8e1-6271-43f2-9a41-2957482aab6c
		summarizeBy: none
		sourceColumn: Discharge Date

		variation Variation
			isDefault
			relationship: ecc53ca9-ad89-456a-8157-c5f461820071
			defaultHierarchy: LocalDateTable_3fbd6332-b26e-4080-bd05-3ac6985d8ff1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Medication
		dataType: string
		lineageTag: 41b316db-7ef8-43ef-b7d8-5941ad056972
		summarizeBy: none
		sourceColumn: Medication

		annotation SummarizationSetBy = Automatic

	column 'Test Results'
		dataType: string
		lineageTag: 9153f2a5-bc46-41f5-b499-3105d406256e
		summarizeBy: none
		sourceColumn: Test Results

		annotation SummarizationSetBy = Automatic

	column 'Hospital Latitude'
		dataType: double
		lineageTag: 1428bfc4-e77e-4b6e-9963-8676fa0d6283
		summarizeBy: none
		sourceColumn: Hospital Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Hospital Longitude'
		dataType: double
		lineageTag: 313fee4b-38c1-4e63-a115-e527c560902c
		summarizeBy: sum
		sourceColumn: Hospital Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Age Group'
		dataType: string
		lineageTag: c7669fa0-f268-466b-9c63-249f0c9348c8
		summarizeBy: none
		sourceColumn: Age Group
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: ed6d12bf-db83-4057-b75b-80ad990185b8
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	column 'Length of Stay' = DATEDIFF(HealthData[Date of Admission],HealthData[Discharge Date],DAY)
		formatString: 0
		lineageTag: a036c688-0835-4af7-b915-0debc966669a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Condition ID'
		dataType: int64
		formatString: 0
		lineageTag: 0dac4d97-44f9-4f5f-99fe-5ba9017483e5
		summarizeBy: none
		sourceColumn: Condition ID

		annotation SummarizationSetBy = Automatic

	column Hospitals = ```
			
			SWITCH(
			    TRUE(),
			    HealthData[Hospital] = "Cedars-Sinai Medical Center", "Cedars-Sinai Medical Center",
			    HealthData[Hospital] = "Cleveland Clinic", "Cleveland Clinic",
			    HealthData[Hospital] = "Houston Methodist Hospital", "Houston Methodist Hospital",
			    HealthData[Hospital] = "Johns Hopkins Hospital", "Johns Hopkins Hospital",
			    HealthData[Hospital] = "Massachusetts General Hospital", "Massachusetts General Hospital",
			    HealthData[Hospital] = "Mayo Clinic", "Mayo Clinic",
			    HealthData[Hospital] = "NewYork-Presbyterian Hospital", "NewYork-Presbyterian Hospital",
			    HealthData[Hospital] = "Northwestern Memorial Hospital", "Northwestern Memorial Hospital",
			    HealthData[Hospital] = "UCLA Medical Center", "UCLA Medical Center",
			    HealthData[Hospital] = "UCSF Medical Center", "UCSF Medical Center",
			    "Other"
			)
			
			```
		lineageTag: b2ac303a-e569-4610-8ed1-fccee9eee5d3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'LOS Bucket' = ```
			
			SWITCH(
			    TRUE(),
			    HealthData[Length of Stay] <= 3, "Short Stay (1-3)",
			    HealthData[Length of Stay] <= 7, "Moderate Stay (4-7)",
			    HealthData[Length of Stay] <= 14, "Long Stay (8-14)",
			    "Extended Stay (15+)"
			)
			
			```
		lineageTag: d140b8e7-309e-4197-a43a-b95061255053
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition HealthData = m
		mode: import
		queryGroup: 'Fact Table'
		source =
				let
				    Source = Excel.Workbook(File.Contents(DataFolder & FilePath), null, true),
				    Data_Sheet = Source{[Item="Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Patient ID", type text}, {"Age", Int64.Type}, {"Gender", type text}, {"Blood Type", type text}, {"Medical Condition", type text}, {"Date of Admission", type date}, {"Doctor", type text}, {"Hospital", type text}, {"Insurance Provider", type text}, {"Billing Amount", type number}, {"Room Number", Int64.Type}, {"Admission Type", type text}, {"Discharge Date", type date}, {"Medication", type text}, {"Test Results", type text}, {"Hospital Latitude", type number}, {"Hospital Longitude", type number}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "Age Group", each if [Age] <= 24 then "18-24yrs" else if [Age] <= 34 then "25-34yrs" else if [Age] <= 49 then "35-49yrs" else if [Age] <= 64 then "50-64yrs" else if [Age] <= 79 then "65-79yrs" else "80-89yrs"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Age Group", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Sort", each if [Age] <= 24 then "1" else if [Age] <= 34 then "2" else if [Age] <= 49 then "3" else if [Age] <= 64 then "4" else if [Age] <= 79 then "5" else "6"),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"Sort", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type2", {"Medical Condition"}, DimCondition, {"Medical Condition"}, "DimCondition", JoinKind.LeftOuter),
				    #"Expanded DimCondition" = Table.ExpandTableColumn(#"Merged Queries", "DimCondition", {"Condition ID"}, {"Condition ID"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Expanded DimCondition",{"Patient ID", "Age", "Gender", "Blood Type", "Date of Admission", "Doctor", "Hospital", "Insurance Provider", "Billing Amount", "Room Number", "Admission Type", "Discharge Date", "Medication", "Test Results", "Hospital Latitude", "Hospital Longitude", "Age Group", "Sort", "Condition ID"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

